###########################################################################################################
#|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
###########################################################################################################
#                                                                                                         #
#                                          ~~ RustyConnector ~~                                           #
#             __     __   ______   ______   ______   ______   ______   __  __   ______  ______            #
#            /\ \  _ \ \ /\  ___\ /\  == \ /\  ___\ /\  __ \ /\  ___\ /\ \/ /  /\  ___\/\__  _\           #
#            \ \ \/ ".\ \\ \  __\ \ \  __< \ \___  \\ \ \/\ \\ \ \____\ \  _"-.\ \  __\\/_/\ \/           #
#             \ \__/".~\_\\ \_____\\ \_____\\/\_____\\ \_____\\ \_____\\ \_\ \_\\ \_____\ \ \_\           #
#              \/_/   \/_/ \/_____/ \/_____/ \/_____/ \/_____/ \/_____/ \/_/\/_/ \/_____/  \/_/           #
#                            ______   ______   __   _____    ______   ______                              #
#                           /\  == \ /\  == \ /\ \ /\  __-. /\  ___\ /\  ___\                             #
#                           \ \  __< \ \  __< \ \ \\ \ \/\ \\ \ \__ \\ \  __\                             #
#                            \ \_____\\ \_\ \_\\ \_\\ \____- \ \_____\\ \_____\                           #
#                             \/_____/ \/_/ /_/ \/_/ \/____/  \/_____/ \/_____/                           #
#                                                                                                         #
#                                                                                                         #
#                                                                                                         #
#                             Welcome to the RustyConnector WebSocket Bridge!                             #
#                                                                                                         #
#                            -------------------------------------------------                            #
#                                                                                                         #
#                             | Allows you to setup a RustyConnector network                              #
#                             | without Redis or RabbitMQ!                                                #
#                                                                                                         #
#                            -------------------------------------------------                            #
#                                                                                                         #
###########################################################################################################
#|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
###########################################################################################################
websocket:
    host: "0.0.0.0"
    port: 8080

    #
    # Should connections from domains other than the host's be allowed?
    # This allows connections from ANYWHERE!
    #
    cors-enabled: false

############################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#                     Secure Connector                     #
#                                                          #
#               ---------------------------                #
#                                                          #
# | Configure Secure Connector to add an extra level of    #
# | authentication to your websocket bridge.               #
#                                                          #
# | If enabled, all RustyConnector instance that attempt   #
# | to connect to the bridge will be required to provide   #
# | the same connection key that's listed below.           #
#                                                          #
#               ----------------------------               #
#                                                          #
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
############################################################
secure-connector:
    enabled: true

    #
    # The connection key to validate new connections with.
    # All RustyConnector instances will be required to use the same key that's listed here when they connect.
    # The key must be 32 characters long.
    #
    # The key that loads with this file is a default that all copies of WebSocket Bridge, have!
    # Make sure you change it!
    #
    connection-key: "29c62552418509be64270534f290800d"

    ############################################################################
    #||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
    #                                  Timeout                                 #
    #                                                                          #
    #                       ---------------------------                        #
    # | How long a Secure Connector request token is allowed to exist for      #
    # | before expiring.                                                       #
    #                                                                          #
    # | If you don't know what this means, just leave the default.             #
    #                                                                          #
    # | This data value is a Liquid Timestamp. Read more here:                 #
    # https://github.com/Aelysium-Group/rusty-connector/wiki/Liquid-Timestamps #
    #                                                                          #
    #   NOTE: The Liquid Timestamp "NEVER" is not allowed here!                #
    #                                                                          #
    #||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
    ############################################################################
    timeout: 5 SECONDS