package group.aelysium.rustyconnector.core.lib.util.logger;

public enum LangKey {
    WORDMARK,
    INFO_HEADER,
    REGISTERED_FAMILIES_HEADER,
    REGISTERED_SERVERS_HEADER,
    BOXED_MESSAGE,

    ICON_REQUEST_REGISTRATION,
    ICON_REGISTERED,
    ICON_REQUESTING_UNREGISTRATION,
    ICON_UNREGISTERED,
    ICON_CANCELED,
    ICON_CALL_FOR_REGISTRATION,
    ICON_FAMILY_BALANCING,
    ICON_PING,
    ICON_PONG,
}
