name: Build RC
on:
  push:
    branches:
      - '**'# matches every branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute Gradle build
        working-directory: ./plugin
        run: chmod +x gradlew && ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RustyConnector
          path: |
            ${{ github.workspace }}/plugin/paper/build/libs/paper.jar
            ${{ github.workspace }}/plugin/velocity/build/libs/velocity.jar
