############################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#                Welcome to RustyConnector!                #
#                                                          #
#               ---------------------------                #
# | RustyConnector is your go-to load-balancer and player  #
# | manager for Minecraft networks!                        #
#                                                          #
# | Built for usage on high-traffic networks;              #
# | RustyConnector is meant to be scalable and easy        #
# | to maintain!                                           #
#               ---------------------------                #
#                       Produced by:                       #
#                        Aelysium                          #
#               ---------------------------                #
#                                                          #
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
############################################################
#
# Do not touch this value, it might totally mess up your entire plugin!
# And that's the last thing anyone wants :)
#
config-version: "0.1"



############################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#                       Registration                       #
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
############################################################

#
# Private key is used to validate server connections.
# This way external servers can't appear and add themselves to the proxy network pool.
# This value should be changed periodically for security purposes.
#
# Set this value so that it matches whatever is set in your proxy.
#
private-key: ""

#
# This field is not required. If you don't set this field the proxy will take this server's IP Address
# and combine it in with a generated data value. It will then hash the output and use that to identify this server.
# If you name the server yourself, you will have a much easier time reading permissions and other data.
#
server-name: ""

############################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#                Family and Load Balancing                 #
#                                                          #
#               ---------------------------                #
# | Families are a collection of servers. To register      #
# | new servers into a family, you need to configure       #
# | your sub-servers appropriately.                        #
#                                                          #
# | If your sub-servers use family names that don't match  #
# | what you define in your  proxy, they will not          #
# | be registered.                                         #
#               ---------------------------                #
#                                                          #
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
############################################################
#
# The name of the family that this plugin should be registered into.
# If this name does not match one of the names listed on your proxy. This server will not get registered.
#
family: "lobby"

#########################
#     Load Balancing    #
#########################
#
# If the family that this server is associated with; has load balancing set to: CASCADE.
# You need to define indexes so that the proxy knows what order to fill the servers.
# The proxy will look at whichever server has the highest index and will start filling that up until it's reached its soft player cap.
#
cascade-priority-index: 0

#########################
#      Player Caps      #
#########################
#
# The soft player cap will define, at what point, this server should stop accepting regular players.
# This allows you to mark the server as "full" while still allowing extra space for VIP and staff.
#
# To allow players to join past this point, you can give them one of two permissions:
# rustyconnector.<family name>.softCapBypass - Bypass the soft cap of any server inside of this family
# rustyconnector.<family name>.<server name>.softCapBypass - Bypass the soft cap of only this server in particular
#
soft-player-cap: 20

#
# The hard player cap is the point at which no more players are allowed to join the server.
# if you wish to still allow high-level staff to access a server at hard player cap. You can grant them the permission:
# rustyconnector.admin.hardCapBypass
#
hard-player-cap: 30

#
# If you set the soft cap and the hard cap to be the exact same value. This server will ignore the soft cap
# and only allow players to join up to the value of the hard cap.
#

############################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#                          Redis                           #
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
############################################################

#
# Redis is required in order to provide quick and easy syncing between the proxy and sub-servers
#
# Every server that you define will connect to your Redis database. Make sure your database has enough available "connections"
# so that you don't run into issues creating new servers and registering them.
#
redis:
  host: "localhost",
  port: "3306",
  password: "password",

  #
  # The name of the data channel that sync information should be sent over.
  # If you don't know what this is, don't mess with it! The default value here is fine.
  # You probably won't break anything, but you generally just shouldn't touch things you don't understand.
  #
  # NOTE: Make sure that, if you do change this. It matches the data-channel that is set in your proxy!
  #
  data-channel: "rustyConnector-sync"


############################################################
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
#                        Whitelist                         #
#                                                          #
#               ---------------------------                #
# | RustyConnector attempts to be as flexible as possible  #
# | when configuring whitelists!                           #
# | To setup a whitelist, you'll need to navigate to the   #
# | "whitelists" folder and follow the directions in the   #
# | provided whitelist-template.                           #
#                                                          #
# | More often than not, you will have multiple whitelist  #
# | configurations that you may want to switch between     #
# | during various points in your network's lifetime.      #
# | This system allows you to setup as many pre-defined    #
# | whitelists as you'd like, and enable or switch between #
# | then whenever you want!                                #
#               ---------------------------                #
#                                                          #
#||||||||||||||||||||||||||||||||||||||||||||||||||||||||||#
############################################################

#
# If you set this to be on. You will be turning on a whitelist which will **effect your entire proxy**!
# If you only want to effect certain families or individual servers. Look into the appropriate configuration locations!
#
use-whitelist: false
whitelist: "whitelist-template"